# Because Tugboat does not run on Kubernetes, we'll need to run a different docker configuration.  We'll match our own
# docker images as closely as we can to Lagoon's, but we'll need to combine some services to get a similar result.
services:
  # Define our standard webserver.
  webserver:
    #image: uselagoon/php-8.1-cli-drupal:latest
    #image: uselagoon/nginx-drupal:latest
    #image: uselagoon/php-8.1-fpm:latest
    image: tugboatqa/php-nginx:8.1-fpm

    # Set this service as the default to handle HTTP requests.
    default: true

    # Ensure we have our database loaded first.
    depends: database

    # Run our phased commands to build the server and install the site.
    commands:
      # The INIT phase is for initializing the server itself.
      init:
        # Set some helpful aliases for the cli and add the composer bin to the PATH.
        - echo "alias ll='ls -la'" >> /root/.bashrc
        - echo "export PATH=$PATH:${TUGBOAT_ROOT}/vendor/bin" >> /root/.bashrc

        # Install opcache.
        - docker-php-ext-install opcache

        # Install Lagoon Sync so we can fetch the files.
        - DOWNLOAD_PATH=$(curl -sL "https://api.github.com/repos/uselagoon/lagoon-sync/releases/latest" | grep "browser_download_url" | cut -d \" -f 4 | grep linux_amd64) && wget -O /usr/local/bin/lagoon-sync $DOWNLOAD_PATH && chmod a+x /usr/local/bin/lagoon-sync

        # This may not be needed as lagoon-sync can handle getting assets from the Lagoon system.  This CLI allows us
        # to interact with the Lagoon environments for all sorts of other things.

        # Install the Lagoon CLI.
        #- curl -L "https://github.com/uselagoon/lagoon-cli/releases/download/v0.18.1/lagoon-cli-v0.18.1-linux-amd64" -o /usr/local/bin/lagoon
        #- chmod +x /usr/local/bin/lagoon

        # Create the ~/.lagoon.yml file, configure Lagoon, and authenticate.
        #- lagoon config add --force --lagoon "${LAGOON_PROJECT}" --graphql https://api.lagoon.amazeeio.cloud/graphql --hostname ssh.lagoon.amazeeio.cloud --port 32222 --ui https://dashboard.amazeeio.cloud
        #- lagoon config default --lagoon "${LAGOON_PROJECT}"
        #- lagoon login

      # The UPDATE phase is for importing assets and dependencies.
      update:
        # Create the necessary private directories outside the webroot. (see settings.tugboat.php)
        - mkdir -p "${TUGBOAT_ROOT}/files-private" "${TUGBOAT_ROOT}/config"
        - chgrp -R www-data "${TUGBOAT_ROOT}/files-private"
        - chmod -R 664 "${TUGBOAT_ROOT}/files-private"

        # Install/update packages managed by composer, including drush.
        - composer install --optimize-autoloader

        # Link the document root to the expected path. This example links /web
        # to the docroot.
        - ln -snf "${TUGBOAT_ROOT}/web" "${DOCROOT}"

        # Use the tugboat-specific Drupal settings.
        - cp "${TUGBOAT_ROOT}/.tugboat/settings.tugboat.php" "${DOCROOT}/sites/default/settings.local.php"

        # Symlink your custom code into Drupal's installation.
        #- ln -snf "${TUGBOAT_ROOT}/custom/themes" "${DOCROOT}/themes/custom"
        #- ln -snf "${TUGBOAT_ROOT}/custom/modules" "${DOCROOT}/modules/custom"

        # Set public file permissions such that Drupal will not complain.
        # A translations file is needed to enable SFP.
        - mkdir -p "${DOCROOT}/sites/default/files/translations"
        - chgrp -R www-data "${DOCROOT}/sites/default/files"
        - find "${DOCROOT}/sites/default/files" -type d -exec chmod 2775 {} \;
        - find "${DOCROOT}/sites/default/files" -type f -exec chmod 0664 {} \;

        # Import files from Lagoon.
        # Due to Lagoon's config, we need to match the destination path to the source path.
        # Alternatively, you can comment this out and enable Stage File Proxy in the 'build' phase.
#        - mkdir -p /app/web/sites/default/files
#        - ln -snf /app/web/sites/default/files "${DOCROOT}/sites/default/files"
#        - lagoon-sync sync files -e "${LAGOON_ENV}" --no-interaction

      # The BUILD phase is for running scripts to build and prepare your website.
      build:
        # Run the drush commands needed for a site with an imported database.
        - vendor/bin/drush cache:rebuild
        - vendor/bin/drush config:import -y
        - vendor/bin/drush updatedb -y
        - vendor/bin/drush cache:rebuild

        # File Sync Alternative: Enable Stage File Proxy (settings are in settings.tugboat.php)
        # This must be enabled after the config sync, otherwise Drupal will disable it when it runs the config sync.
        - vendor/bin/drush -r "${DOCROOT}" pm-enable --yes stage_file_proxy


  # Define our database service.
  database:
    #image: uselagoon/mariadb-10.6-drupal:latest
    image: tugboatqa/mariadb:10.6

    # Checkout the codebase so we have access to the .lagoon.yml file to sync the DB.
    checkout: true

    # Run the commands to build out and install our database.
    commands:
      # The INIT phase initializes the server.
      init:
        # Set some helpful aliases for the cli and add the composer bin to the PATH.
        - echo "alias ll='ls -la'" >> /root/.bashrc

        # Increase the allowed packet size to 512MB.
        - mysql -e "SET GLOBAL max_allowed_packet=536870912;"

        # Ensure this packet size persists even if MySQL restarts.
        - echo "max_allowed_packet=536870912" >> /etc/mysql/conf.d/tugboat.cnf

        # Install Lagoon Sync so we can fetch a database.
        - DOWNLOAD_PATH=$(curl -sL "https://api.github.com/repos/uselagoon/lagoon-sync/releases/latest" | grep "browser_download_url" | cut -d \" -f 4 | grep linux_amd64) && wget -O /usr/local/bin/lagoon-sync $DOWNLOAD_PATH && chmod a+x /usr/local/bin/lagoon-sync

      # The UPDATE phase downloads and installs databases, assets, libraries, and dependencies.
      update:
        # Fetch the database from Lagoon and import it.
        # @TODO: Change this to rsync a pre-dumped file so we're not dumping the database on every build.
        - lagoon-sync sync mariadb -e "${LAGOON_ENV}" --skip-target-cleanup=true --skip-target-import=true --no-interaction
        - zcat /tmp/lagoon_sync_mariadb_*.sql.gz | mysql tugboat
        - rm /tmp/lagoon_sync_mariadb_*.sql.gz

  # Define our search engine.
  #solr:
    #image: uselagoon/solr-8-drupal:latest
    #image: tugboatqa/solr:8


  # Define our caching service.
  #redis:
    #image: uselagoon/redis-6:latest
    #image: tugboatqa/redis:6
